-- AlterTable
ALTER TABLE `client` ADD COLUMN `plansId` VARCHAR(191) NULL,
    ADD COLUMN `status` ENUM('CREADO', 'INSTALADO', 'ACTIVO', 'INACTIVO', 'BAJA', 'PLANIFICADO') NOT NULL DEFAULT 'CREADO';

-- AddForeignKey
ALTER TABLE `Client` ADD CONSTRAINT `Client_plansId_fkey` FOREIGN KEY (`plansId`) REFERENCES `Plans`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
