-- AlterTable
ALTER TABLE `roadmap` ADD COLUMN `status` ENUM('PLANIFICADA', 'PROCESO', 'CERRADA') NOT NULL DEFAULT 'PLANIFICADA';

-- AlterTable
ALTER TABLE `roadmapclients` ADD COLUMN `status` ENUM('PLANIFICADA', 'PROCESO', 'FALLIDO', 'INSTALADA') NOT NULL DEFAULT 'PLANIFICADA';
